// Registration
export const REGISTER_RESET = 'REGISTER_RESET';
export const REGISTER_REQUEST = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// Login
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Logout
export const LOGOUT_RESET = 'LOGOUT_RESET';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// User
export const USER_RESET = 'USER_RESET';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';

export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

// Users
export const USERS_RESET = 'USERS_RESET';
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILED = 'USERS_FAILED';

export const USERS_UPDATE_RESET = 'USERS_UPDATE_RESET';
export const USERS_UPDATE_REQUEST = 'USERS_UPDATE_REQUEST';
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';
export const USERS_UPDATE_FAILED = 'USERS_UPDATE_FAILED';

// Maps
export const MAPS_RESET = 'MAPS_RESET';
export const MAPS_REQUEST = 'MAPS_REQUEST';
export const MAPS_SUCCESS = 'MAPS_SUCCESS';
export const MAPS_FAILED = 'MAPS_FAILED';

// System
export const SYSTEM_PARAMETERS_RESET = 'SYSTEM_PARAMETERS_RESET';
export const SYSTEM_PARAMETERS_REQUEST = 'SYSTEM_PARAMETERS_REQUEST';
export const SYSTEM_PARAMETERS_SUCCESS = 'SYSTEM_PARAMETERS_SUCCESS';
export const SYSTEM_PARAMETERS_FAILED = 'SYSTEM_PARAMETERS_FAILED';

export const SYSTEM_PARAMETERS_UPDATE_RESET = 'SYSTEM_PARAMETERS_UPDATE_RESET';
export const SYSTEM_PARAMETERS_UPDATE_REQUEST = 'SYSTEM_PARAMETERS_UPDATE_REQUEST';
export const SYSTEM_PARAMETERS_UPDATE_SUCCESS = 'SYSTEM_PARAMETERS_UPDATE_SUCCESS';
export const SYSTEM_PARAMETERS_UPDATE_FAILED = 'SYSTEM_PARAMETERS_UPDATE_FAILED';

export const SYSTEM_BACKUP_RESET = 'SYSTEM_BACKUP_RESET';
export const SYSTEM_BACKUP_REQUEST = 'SYSTEM_BACKUP_REQUEST';
export const SYSTEM_BACKUP_SUCCESS = 'SYSTEM_BACKUP_SUCCESS';
export const SYSTEM_BACKUP_FAILED = 'SYSTEM_BACKUP_FAILED';

//Restore and change password 
export const RESTORE_RESET = 'RESTORE_RESET';
export const RESTORE_REQUEST = 'RESTORE_REQUEST';
export const RESTORE_SUCCESS = 'RESTORE_SUCCESS';
export const RESTORE_FAILED = 'RESTORE_FAILED';

export const CHANGEPASSWORD_RESET = 'CHANGEPASSWORD_RESET';
export const CHANGEPASSWORD_REQUEST = 'CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAILED = 'CHANGEPASSWORD_FAILED';