// Registration
export const REGISTER_RESET = 'REGISTER_RESET';
export const REGISTER_REQUEST = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// Login
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Logout
export const LOGOUT_RESET = 'LOGOUT_RESET';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// User
export const USER_RESET = 'USER_RESET';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';

export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

// Users
export const USERS_RESET = 'USERS_RESET';
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILED = 'USERS_FAILED';

export const USERS_UPDATE_RESET = 'USERS_UPDATE_RESET';
export const USERS_UPDATE_REQUEST = 'USERS_UPDATE_REQUEST';
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';
export const USERS_UPDATE_FAILED = 'USERS_UPDATE_FAILED';

// Products
export const PRODUCTS_RESET = 'PRODUCTS_RESET';
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const PRODUCTS_UPDATE_RESET = 'PRODUCTS_UPDATE_RESET';
export const PRODUCTS_UPDATE_REQUEST = 'PRODUCTS_UPDATE_REQUEST';
export const PRODUCTS_UPDATE_SUCCESS = 'PRODUCTS_UPDATE_SUCCESS';
export const PRODUCTS_UPDATE_FAILED = 'PRODUCTS_UPDATE_FAILED';


// Orders
export const ORDERS_RESET = 'ORDERS_RESET';
export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAILED = 'ORDERS_FAILED';

export const ORDERS_UPDATE_RESET = 'ORDERS_UPDATE_RESET';
export const ORDERS_UPDATE_REQUEST = 'ORDERS_UPDATE_REQUEST';
export const ORDERS_UPDATE_SUCCESS = 'ORDERS_UPDATE_SUCCESS';
export const ORDERS_UPDATE_FAILED = 'ORDERS_UPDATE_FAILED';

// Maps
export const MAPS_RESET = 'MAPS_RESET';
export const MAPS_REQUEST = 'MAPS_REQUEST';
export const MAPS_SUCCESS = 'MAPS_SUCCESS';
export const MAPS_FAILED = 'MAPS_FAILED';

// System
export const SYSTEM_PARAMETERS_RESET = 'SYSTEM_PARAMETERS_RESET';
export const SYSTEM_PARAMETERS_REQUEST = 'SYSTEM_PARAMETERS_REQUEST';
export const SYSTEM_PARAMETERS_SUCCESS = 'SYSTEM_PARAMETERS_SUCCESS';
export const SYSTEM_PARAMETERS_FAILED = 'SYSTEM_PARAMETERS_FAILED';

export const SYSTEM_PARAMETERS_UPDATE_RESET = 'SYSTEM_PARAMETERS_UPDATE_RESET';
export const SYSTEM_PARAMETERS_UPDATE_REQUEST = 'SYSTEM_PARAMETERS_UPDATE_REQUEST';
export const SYSTEM_PARAMETERS_UPDATE_SUCCESS = 'SYSTEM_PARAMETERS_UPDATE_SUCCESS';
export const SYSTEM_PARAMETERS_UPDATE_FAILED = 'SYSTEM_PARAMETERS_UPDATE_FAILED';

export const SYSTEM_BACKUP_RESET = 'SYSTEM_BACKUP_RESET';
export const SYSTEM_BACKUP_REQUEST = 'SYSTEM_BACKUP_REQUEST';
export const SYSTEM_BACKUP_SUCCESS = 'SYSTEM_BACKUP_SUCCESS';
export const SYSTEM_BACKUP_FAILED = 'SYSTEM_BACKUP_FAILED';

//Restore
export const RESTORE_RESET = 'RESTORE_RESET';
export const RESTORE_REQUEST = 'RESTORE_REQUEST';
export const RESTORE_SUCCESS = 'RESTORE_SUCCESS';
export const RESTORE_FAILED = 'RESTORE_FAILED';

//Change password
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

// Clients
export const CLIENTS_RESET = 'CLIENTS_RESET';
export const CLIENTS_REQUEST = 'CLIENTS_REQUEST';
export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS';
export const CLIENTS_FAILED = 'CLIENTS_FAILED';

export const CLIENTS_UPDATE_RESET = 'CLIENTS_UPDATE_RESET';
export const CLIENTS_UPDATE_REQUEST = 'CLIENTS_UPDATE_REQUEST';
export const CLIENTS_UPDATE_SUCCESS = 'CLIENTS_UPDATE_SUCCESS';
export const CLIENTS_UPDATE_FAILED = 'CLIENTS_UPDATE_FAILED';